class CreateUserGroups < ActiveRecord::Migration[8.1]
  def change
    create_table "groups", id: :serial do |t|
      t.string "code",          limit: 64, null: false, comment: "Code has to be unique in a hierarchical level"
      t.json "name",                                    comment: "Name is translated."
      t.json "description",                             comment: "Description is translated."
      t.uuid "uuid",            null: false, default: -> { "gen_random_uuid()" }, comment: "May be generated by OmniAuth"
      t.boolean "is_active",    default: true, comment: "As nothing can be deleted, flags objects removed from the knowledge base"
      t.integer "owner_id",      null: false, comment: "Trace of the user or process who owns the record"
      t.integer "created_by_id", null: false, comment: "Trace of the user or process who created the record"
      t.integer "updated_by_id", null: false, comment: "Trace of the last user or process who updated the record"
      t.string "sort_code",                             comment: "Code used for sorting displayed indexes"
      t.timestamps

      t.index [ "code" ],          name: "index_group_on_code", unique: true
      t.index [ "sort_code" ],     name: "index_groups_on_sort_code"
      t.index [ "uuid" ],          name: "index_groups_on_uuid", unique: true
      t.index [ "owner_id" ],      name: "index_groups_on_owner_id"
      t.index [ "created_by_id" ], name: "index_groups_on_created_by_id"
      t.index [ "updated_by_id" ], name: "index_groups_on_updated_by_id"
    end

    create_table "users_groups", id: :serial do |t|
      t.references :user,  index: false
      t.references :group, index: true
      t.boolean "is_active",     default: true,  comment: "As nothing can be deleted, flags objects removed from the knowledge base"
      t.datetime "active_from",  default: -> { 'current_date' }, comment: "Validity period"
      t.datetime "active_to"
      t.boolean "is_main_group", default: false, comment: "User's main group allows notificaions routing."
      t.timestamps

      t.index [ "user_id", "group_id", "is_active" ], name: "index_user_group", unique: true
    end

    add_foreign_key :groups, :users, column: :owner_id
    add_foreign_key :groups, :users, column: :created_by_id
    add_foreign_key :groups, :users, column: :updated_by_id
    add_foreign_key :users_groups, :users
    add_foreign_key :users_groups, :groups
  end
end
